apiVersion: v1 
kind: Service
metadata: 
  name: notes-app-service
  namespace: notes-app

spec: 
   selector: 
      app: notes-app # Matches Deployment label
   ports: 
    - protocol: TCP
      port: 8000 # Service port
      targetPort: 8000 # Container port
   type: ClusterIP # Internal service
